audio-file-auto=fuzzy
auto-window-resize=no
embeddedfonts=no
fixed-vo=yes
input-ipc-server=\\.\pipe\mpv_pipe
keepaspect-window=no
save-position-on-quit=yes
sub-ass-override=force
sub-auto=fuzzy
sub-font=Calibri
sub-visibility=yes